### ISSUE TITLE
Consider suggesting to not create an unintilized dst Vec in the first place (Example 1 in Undefined Behavior)

### ISSUE THREAD

**Issue by feature-engineer** [luk6xff/luk6xff.github.io#3]
I know that the point of this comparison is to show how accessing an uninitialized Vec results in a UB in C++, and a compilation error in Rust. But I think that it is still worth mentioning that this is a bad form in both languages (even with the suggested fix of pre-allocating dst). 

The preferred way to write that function is `src.iter().map(|&x| x.pow(2)).collect()` (and `return src | std::views::transform([](int v) { return std::pow(v, 2); }) | std::ranges::to<std::vector<int>>();` for c++)

**Comment by luk6xff** [comment]
Can you add it as an additional solution besides the ne proposed ?
